name: CI for BufferQueue

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architectire: '64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run main test with flake8
      run: |
        python -m flake8 .
    - name: Run main test with unittest to Fifo
      run: |
        python -m unittest tests/main_tests.py
